name = "Quill Theme"
version = "0.2.3"
authors = ["Quill <dev@quill.do>"]
description = "🪶 Quill theme for Zed"
repository = "https://github.com/CraftQuill/zed-theme-quill"
id = "quill-theme"
schema_version = 1
